spring:
  application:
    name: API-GATEWAY
  cloud:
    refresh:
      enabled: false
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    preferIpAddress: true
    instanceId: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:localhost.p12
    key-store-password: localhost
    key-alias: localhost