[package]
org = "ricco"
name = "bal_api_gateway"
version = "1.0.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.10.6"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.10.0"